/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as MeRouteImport } from './routes/me'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FacultiesRouteImport } from './routes/faculties'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ToolsQrRouteImport } from './routes/tools.qr'
import { Route as ToolsPdfRouteImport } from './routes/tools.pdf'
import { Route as ToolsOcrRouteImport } from './routes/tools.ocr'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as PostNewRouteImport } from './routes/post.new'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as MarketNewRouteImport } from './routes/market.new'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as GamesPuzzleRouteImport } from './routes/games.puzzle'
import { Route as FacultyIdRouteImport } from './routes/faculty.$id'
import { Route as DepartmentIdRouteImport } from './routes/department.$id'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as CourseIdRouteImport } from './routes/course.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BooksReadIdRouteImport } from './routes/books_.read.$id'
import { Route as ApiPublicHooksSyncLibraryBooksRouteImport } from './routes/api/public/hooks/sync-library-books'
import { Route as ApiPublicHooksSyncCoursesRouteImport } from './routes/api/public/hooks/sync-courses'
import { Route as ApiPublicHooksGenerateNovelRouteImport } from './routes/api/public/hooks/generate-novel'
import { Route as ApiPublicHooksGenerateBookCoversRouteImport } from './routes/api/public/hooks/generate-book-covers'
import { Route as ApiPublicHooksGenerateBlogRouteImport } from './routes/api/public/hooks/generate-blog'
import { Route as ApiPublicHooksCacheBookPdfRouteImport } from './routes/api/public/hooks/cache-book-pdf'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesRoute = FacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQrRoute = ToolsQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPdfRoute = ToolsPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsOcrRoute = ToolsOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => ToolsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostNewRoute = PostNewRouteImport.update({
  id: '/post/new',
  path: '/post/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketNewRoute = MarketNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MarketRoute,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketRoute,
} as any)
const GamesPuzzleRoute = GamesPuzzleRouteImport.update({
  id: '/puzzle',
  path: '/puzzle',
  getParentRoute: () => GamesRoute,
} as any)
const FacultyIdRoute = FacultyIdRouteImport.update({
  id: '/faculty/$id',
  path: '/faculty/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentIdRoute = DepartmentIdRouteImport.update({
  id: '/department/$id',
  path: '/department/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIdRoute = CourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BooksReadIdRoute = BooksReadIdRouteImport.update({
  id: '/books_/read/$id',
  path: '/books/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncLibraryBooksRoute =
  ApiPublicHooksSyncLibraryBooksRouteImport.update({
    id: '/api/public/hooks/sync-library-books',
    path: '/api/public/hooks/sync-library-books',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncCoursesRoute =
  ApiPublicHooksSyncCoursesRouteImport.update({
    id: '/api/public/hooks/sync-courses',
    path: '/api/public/hooks/sync-courses',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateNovelRoute =
  ApiPublicHooksGenerateNovelRouteImport.update({
    id: '/api/public/hooks/generate-novel',
    path: '/api/public/hooks/generate-novel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateBookCoversRoute =
  ApiPublicHooksGenerateBookCoversRouteImport.update({
    id: '/api/public/hooks/generate-book-covers',
    path: '/api/public/hooks/generate-book-covers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateBlogRoute =
  ApiPublicHooksGenerateBlogRouteImport.update({
    id: '/api/public/hooks/generate-blog',
    path: '/api/public/hooks/generate-blog',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCacheBookPdfRoute =
  ApiPublicHooksCacheBookPdfRouteImport.update({
    id: '/api/public/hooks/cache-book-pdf',
    path: '/api/public/hooks/cache-book-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/books': typeof BooksRoute
  '/chat': typeof ChatRoute
  '/faculties': typeof FacultiesRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/me': typeof MeRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tools': typeof ToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/course/$id': typeof CourseIdRoute
  '/courses/$id': typeof CoursesIdRoute
  '/department/$id': typeof DepartmentIdRoute
  '/faculty/$id': typeof FacultyIdRoute
  '/games/puzzle': typeof GamesPuzzleRoute
  '/market/$id': typeof MarketIdRoute
  '/market/new': typeof MarketNewRoute
  '/notes/$id': typeof NotesIdRoute
  '/post/$id': typeof PostIdRoute
  '/post/new': typeof PostNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/qr': typeof ToolsQrRoute
  '/courses/': typeof CoursesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/books/read/$id': typeof BooksReadIdRoute
  '/api/public/hooks/cache-book-pdf': typeof ApiPublicHooksCacheBookPdfRoute
  '/api/public/hooks/generate-blog': typeof ApiPublicHooksGenerateBlogRoute
  '/api/public/hooks/generate-book-covers': typeof ApiPublicHooksGenerateBookCoversRoute
  '/api/public/hooks/generate-novel': typeof ApiPublicHooksGenerateNovelRoute
  '/api/public/hooks/sync-courses': typeof ApiPublicHooksSyncCoursesRoute
  '/api/public/hooks/sync-library-books': typeof ApiPublicHooksSyncLibraryBooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/books': typeof BooksRoute
  '/chat': typeof ChatRoute
  '/faculties': typeof FacultiesRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/me': typeof MeRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tools': typeof ToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/course/$id': typeof CourseIdRoute
  '/courses/$id': typeof CoursesIdRoute
  '/department/$id': typeof DepartmentIdRoute
  '/faculty/$id': typeof FacultyIdRoute
  '/games/puzzle': typeof GamesPuzzleRoute
  '/market/$id': typeof MarketIdRoute
  '/market/new': typeof MarketNewRoute
  '/notes/$id': typeof NotesIdRoute
  '/post/$id': typeof PostIdRoute
  '/post/new': typeof PostNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/qr': typeof ToolsQrRoute
  '/courses': typeof CoursesIndexRoute
  '/notes': typeof NotesIndexRoute
  '/books/read/$id': typeof BooksReadIdRoute
  '/api/public/hooks/cache-book-pdf': typeof ApiPublicHooksCacheBookPdfRoute
  '/api/public/hooks/generate-blog': typeof ApiPublicHooksGenerateBlogRoute
  '/api/public/hooks/generate-book-covers': typeof ApiPublicHooksGenerateBookCoversRoute
  '/api/public/hooks/generate-novel': typeof ApiPublicHooksGenerateNovelRoute
  '/api/public/hooks/sync-courses': typeof ApiPublicHooksSyncCoursesRoute
  '/api/public/hooks/sync-library-books': typeof ApiPublicHooksSyncLibraryBooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/books': typeof BooksRoute
  '/chat': typeof ChatRoute
  '/faculties': typeof FacultiesRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/me': typeof MeRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tools': typeof ToolsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/course/$id': typeof CourseIdRoute
  '/courses/$id': typeof CoursesIdRoute
  '/department/$id': typeof DepartmentIdRoute
  '/faculty/$id': typeof FacultyIdRoute
  '/games/puzzle': typeof GamesPuzzleRoute
  '/market/$id': typeof MarketIdRoute
  '/market/new': typeof MarketNewRoute
  '/notes/$id': typeof NotesIdRoute
  '/post/$id': typeof PostIdRoute
  '/post/new': typeof PostNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/pdf': typeof ToolsPdfRoute
  '/tools/qr': typeof ToolsQrRoute
  '/courses/': typeof CoursesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/books_/read/$id': typeof BooksReadIdRoute
  '/api/public/hooks/cache-book-pdf': typeof ApiPublicHooksCacheBookPdfRoute
  '/api/public/hooks/generate-blog': typeof ApiPublicHooksGenerateBlogRoute
  '/api/public/hooks/generate-book-covers': typeof ApiPublicHooksGenerateBookCoversRoute
  '/api/public/hooks/generate-novel': typeof ApiPublicHooksGenerateNovelRoute
  '/api/public/hooks/sync-courses': typeof ApiPublicHooksSyncCoursesRoute
  '/api/public/hooks/sync-library-books': typeof ApiPublicHooksSyncLibraryBooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/books'
    | '/chat'
    | '/faculties'
    | '/games'
    | '/login'
    | '/market'
    | '/me'
    | '/saved'
    | '/search'
    | '/tickets'
    | '/tools'
    | '/blog/$slug'
    | '/course/$id'
    | '/courses/$id'
    | '/department/$id'
    | '/faculty/$id'
    | '/games/puzzle'
    | '/market/$id'
    | '/market/new'
    | '/notes/$id'
    | '/post/$id'
    | '/post/new'
    | '/profile/$id'
    | '/tickets/$id'
    | '/tools/ocr'
    | '/tools/pdf'
    | '/tools/qr'
    | '/courses/'
    | '/notes/'
    | '/books/read/$id'
    | '/api/public/hooks/cache-book-pdf'
    | '/api/public/hooks/generate-blog'
    | '/api/public/hooks/generate-book-covers'
    | '/api/public/hooks/generate-novel'
    | '/api/public/hooks/sync-courses'
    | '/api/public/hooks/sync-library-books'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/books'
    | '/chat'
    | '/faculties'
    | '/games'
    | '/login'
    | '/market'
    | '/me'
    | '/saved'
    | '/search'
    | '/tickets'
    | '/tools'
    | '/blog/$slug'
    | '/course/$id'
    | '/courses/$id'
    | '/department/$id'
    | '/faculty/$id'
    | '/games/puzzle'
    | '/market/$id'
    | '/market/new'
    | '/notes/$id'
    | '/post/$id'
    | '/post/new'
    | '/profile/$id'
    | '/tickets/$id'
    | '/tools/ocr'
    | '/tools/pdf'
    | '/tools/qr'
    | '/courses'
    | '/notes'
    | '/books/read/$id'
    | '/api/public/hooks/cache-book-pdf'
    | '/api/public/hooks/generate-blog'
    | '/api/public/hooks/generate-book-covers'
    | '/api/public/hooks/generate-novel'
    | '/api/public/hooks/sync-courses'
    | '/api/public/hooks/sync-library-books'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/books'
    | '/chat'
    | '/faculties'
    | '/games'
    | '/login'
    | '/market'
    | '/me'
    | '/saved'
    | '/search'
    | '/tickets'
    | '/tools'
    | '/blog/$slug'
    | '/course/$id'
    | '/courses/$id'
    | '/department/$id'
    | '/faculty/$id'
    | '/games/puzzle'
    | '/market/$id'
    | '/market/new'
    | '/notes/$id'
    | '/post/$id'
    | '/post/new'
    | '/profile/$id'
    | '/tickets/$id'
    | '/tools/ocr'
    | '/tools/pdf'
    | '/tools/qr'
    | '/courses/'
    | '/notes/'
    | '/books_/read/$id'
    | '/api/public/hooks/cache-book-pdf'
    | '/api/public/hooks/generate-blog'
    | '/api/public/hooks/generate-book-covers'
    | '/api/public/hooks/generate-novel'
    | '/api/public/hooks/sync-courses'
    | '/api/public/hooks/sync-library-books'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  BooksRoute: typeof BooksRoute
  ChatRoute: typeof ChatRoute
  FacultiesRoute: typeof FacultiesRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  MeRoute: typeof MeRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  ToolsRoute: typeof ToolsRouteWithChildren
  CourseIdRoute: typeof CourseIdRoute
  CoursesIdRoute: typeof CoursesIdRoute
  DepartmentIdRoute: typeof DepartmentIdRoute
  FacultyIdRoute: typeof FacultyIdRoute
  NotesIdRoute: typeof NotesIdRoute
  PostIdRoute: typeof PostIdRoute
  PostNewRoute: typeof PostNewRoute
  ProfileIdRoute: typeof ProfileIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  BooksReadIdRoute: typeof BooksReadIdRoute
  ApiPublicHooksCacheBookPdfRoute: typeof ApiPublicHooksCacheBookPdfRoute
  ApiPublicHooksGenerateBlogRoute: typeof ApiPublicHooksGenerateBlogRoute
  ApiPublicHooksGenerateBookCoversRoute: typeof ApiPublicHooksGenerateBookCoversRoute
  ApiPublicHooksGenerateNovelRoute: typeof ApiPublicHooksGenerateNovelRoute
  ApiPublicHooksSyncCoursesRoute: typeof ApiPublicHooksSyncCoursesRoute
  ApiPublicHooksSyncLibraryBooksRoute: typeof ApiPublicHooksSyncLibraryBooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties': {
      id: '/faculties'
      path: '/faculties'
      fullPath: '/faculties'
      preLoaderRoute: typeof FacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qr': {
      id: '/tools/qr'
      path: '/qr'
      fullPath: '/tools/qr'
      preLoaderRoute: typeof ToolsQrRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/pdf': {
      id: '/tools/pdf'
      path: '/pdf'
      fullPath: '/tools/pdf'
      preLoaderRoute: typeof ToolsPdfRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/ocr': {
      id: '/tools/ocr'
      path: '/ocr'
      fullPath: '/tools/ocr'
      preLoaderRoute: typeof ToolsOcrRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/new': {
      id: '/post/new'
      path: '/post/new'
      fullPath: '/post/new'
      preLoaderRoute: typeof PostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/new': {
      id: '/market/new'
      path: '/new'
      fullPath: '/market/new'
      preLoaderRoute: typeof MarketNewRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof MarketRoute
    }
    '/games/puzzle': {
      id: '/games/puzzle'
      path: '/puzzle'
      fullPath: '/games/puzzle'
      preLoaderRoute: typeof GamesPuzzleRouteImport
      parentRoute: typeof GamesRoute
    }
    '/faculty/$id': {
      id: '/faculty/$id'
      path: '/faculty/$id'
      fullPath: '/faculty/$id'
      preLoaderRoute: typeof FacultyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department/$id': {
      id: '/department/$id'
      path: '/department/$id'
      fullPath: '/department/$id'
      preLoaderRoute: typeof DepartmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$id': {
      id: '/course/$id'
      path: '/course/$id'
      fullPath: '/course/$id'
      preLoaderRoute: typeof CourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/books_/read/$id': {
      id: '/books_/read/$id'
      path: '/books/read/$id'
      fullPath: '/books/read/$id'
      preLoaderRoute: typeof BooksReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-library-books': {
      id: '/api/public/hooks/sync-library-books'
      path: '/api/public/hooks/sync-library-books'
      fullPath: '/api/public/hooks/sync-library-books'
      preLoaderRoute: typeof ApiPublicHooksSyncLibraryBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-courses': {
      id: '/api/public/hooks/sync-courses'
      path: '/api/public/hooks/sync-courses'
      fullPath: '/api/public/hooks/sync-courses'
      preLoaderRoute: typeof ApiPublicHooksSyncCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-novel': {
      id: '/api/public/hooks/generate-novel'
      path: '/api/public/hooks/generate-novel'
      fullPath: '/api/public/hooks/generate-novel'
      preLoaderRoute: typeof ApiPublicHooksGenerateNovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-book-covers': {
      id: '/api/public/hooks/generate-book-covers'
      path: '/api/public/hooks/generate-book-covers'
      fullPath: '/api/public/hooks/generate-book-covers'
      preLoaderRoute: typeof ApiPublicHooksGenerateBookCoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-blog': {
      id: '/api/public/hooks/generate-blog'
      path: '/api/public/hooks/generate-blog'
      fullPath: '/api/public/hooks/generate-blog'
      preLoaderRoute: typeof ApiPublicHooksGenerateBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cache-book-pdf': {
      id: '/api/public/hooks/cache-book-pdf'
      path: '/api/public/hooks/cache-book-pdf'
      fullPath: '/api/public/hooks/cache-book-pdf'
      preLoaderRoute: typeof ApiPublicHooksCacheBookPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GamesRouteChildren {
  GamesPuzzleRoute: typeof GamesPuzzleRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesPuzzleRoute: GamesPuzzleRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface MarketRouteChildren {
  MarketIdRoute: typeof MarketIdRoute
  MarketNewRoute: typeof MarketNewRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketIdRoute: MarketIdRoute,
  MarketNewRoute: MarketNewRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface ToolsRouteChildren {
  ToolsOcrRoute: typeof ToolsOcrRoute
  ToolsPdfRoute: typeof ToolsPdfRoute
  ToolsQrRoute: typeof ToolsQrRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsOcrRoute: ToolsOcrRoute,
  ToolsPdfRoute: ToolsPdfRoute,
  ToolsQrRoute: ToolsQrRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  BooksRoute: BooksRoute,
  ChatRoute: ChatRoute,
  FacultiesRoute: FacultiesRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  MeRoute: MeRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TicketsRoute: TicketsRouteWithChildren,
  ToolsRoute: ToolsRouteWithChildren,
  CourseIdRoute: CourseIdRoute,
  CoursesIdRoute: CoursesIdRoute,
  DepartmentIdRoute: DepartmentIdRoute,
  FacultyIdRoute: FacultyIdRoute,
  NotesIdRoute: NotesIdRoute,
  PostIdRoute: PostIdRoute,
  PostNewRoute: PostNewRoute,
  ProfileIdRoute: ProfileIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  BooksReadIdRoute: BooksReadIdRoute,
  ApiPublicHooksCacheBookPdfRoute: ApiPublicHooksCacheBookPdfRoute,
  ApiPublicHooksGenerateBlogRoute: ApiPublicHooksGenerateBlogRoute,
  ApiPublicHooksGenerateBookCoversRoute: ApiPublicHooksGenerateBookCoversRoute,
  ApiPublicHooksGenerateNovelRoute: ApiPublicHooksGenerateNovelRoute,
  ApiPublicHooksSyncCoursesRoute: ApiPublicHooksSyncCoursesRoute,
  ApiPublicHooksSyncLibraryBooksRoute: ApiPublicHooksSyncLibraryBooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
